# Generated by Django 3.1.6 on 2021-02-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='static/uploads/', verbose_name='file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('options', models.CharField(max_length=150)),
                ('details', models.CharField(max_length=300)),
                ('catalog', models.ForeignKey(on_delete=models.deletion.CASCADE, to='file_app.catalog')),
            ],
        ),
    ]
