# Generated by Django 3.2.3 on 2021-06-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_apply',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Apply'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL'),
        ),
    ]
